// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTM13CKr1nd8uwknCmDSODsiagZFQWHA',
    appId: '1:949828813582:web:5a68f12411c6a418ce4d5f',
    messagingSenderId: '949828813582',
    projectId: 'attach-application-5de85',
    authDomain: 'attach-application-5de85.firebaseapp.com',
    storageBucket: 'attach-application-5de85.firebasestorage.app',
    measurementId: 'G-90JN6D1WTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHfPPH__z0EDgxO6LvyDEdBYr4H0vWdnM',
    appId: '1:949828813582:android:e6854144d1efdae0ce4d5f',
    messagingSenderId: '949828813582',
    projectId: 'attach-application-5de85',
    storageBucket: 'attach-application-5de85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2upE3STR2U1k3kgN6ULRM9CiysgIfLd0',
    appId: '1:949828813582:ios:567681d85a3b875dce4d5f',
    messagingSenderId: '949828813582',
    projectId: 'attach-application-5de85',
    storageBucket: 'attach-application-5de85.firebasestorage.app',
    iosBundleId: 'com.example.attachApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2upE3STR2U1k3kgN6ULRM9CiysgIfLd0',
    appId: '1:949828813582:ios:567681d85a3b875dce4d5f',
    messagingSenderId: '949828813582',
    projectId: 'attach-application-5de85',
    storageBucket: 'attach-application-5de85.firebasestorage.app',
    iosBundleId: 'com.example.attachApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRTM13CKr1nd8uwknCmDSODsiagZFQWHA',
    appId: '1:949828813582:web:a2565d87c6b72178ce4d5f',
    messagingSenderId: '949828813582',
    projectId: 'attach-application-5de85',
    authDomain: 'attach-application-5de85.firebaseapp.com',
    storageBucket: 'attach-application-5de85.firebasestorage.app',
    measurementId: 'G-1J3ZRS18E7',
  );
}
